<?php
apache_setenv('no-gzip', 1); ini_set('zlib.output_compression', 0);
ini_set('output_buffering', 'Off'); ini_set('implicit_flush', 1); ob_implicit_flush(1);    // Disable php_buffering
header("content-type:text/html; charset=UTF-8");
ob_start();    // Ready to display the chat client
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<title>Comet Chat Client</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, target-densitydpi=medium-dpi, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta name="author" content="JimmyLiu" />
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
	<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
	<style type="text/css">body,h1,h2,p,div {font-family: "微软雅黑";}</style>
	<script type="text/javascript">
String.prototype.trim = function() { return this.replace(/(^\s*)|(\s*$)/g, ""); }    // String.trim() extension
$$ = function(id) { return document.getElementById(id); }    // Alias of document.getElementById()
var user = "", lastId = 0;    // UrlEncoded user name, last message ID
var onConnect = function() {    // Connect delegation
	document.getElementById("frame").src = "chat.php?connect="+lastId+"&user="+user+"&rand="+Math.random();
};
var onMsg = function( name, msg ) {    // Message delegation, called by <script> tags generated by server
	var row = document.createElement("p");    // Create a new entry for the message
	row.innerHTML = name.big()+' 说: '.bold()+msg;
	var board = document.getElementById("board");
	board.insertBefore(row, board.lastChild);    // Create a new entry for the message
	if ( (board.offsetHeight/document.body.clientHeight) > 4 )
		board.removeChild(board.firstChild);    // Remove redundant items
	window.scrollBy(0, document.body.clientHeight);  // Scroll to bottom of the page
};
window.onload = function() {
	while ( user==null || user.length<=0 )
		user = encodeURIComponent( window.prompt("请输入您的称呼：", "梓桐妹妹" ) ).trim();
	setTimeout("onConnect()",0);
	document.getElementById("frame").onload = onConnect;
}
function ajaxPost ( url, data, callback ) { var xhr=null;
	try { xhr=new XMLHttpRequest(); }
	catch (IE) {
		try { xhr=new ActiveXObject("Msxml2.XMLHTTP"); }
		catch (oldIE) { xhr=new ActiveXObject("Microsoft.XMLHTTP"); }
	} if ( xhr==null ) return;
	xhr.open( 'POST', url, true ); var request = [];
	for (var key in data) request.push( key+"="+data[key] );
	xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
	xhr.send( request.join('&') );
	xhr.onreadystatechange = function() { if (xhr.readyState==4 && xhr.status==200) { callback(); } };
} function sendMsg(msg) { if (msg.length>0)
	ajaxPost( "chat.php", {"user":user, "msg":encodeURIComponent(msg)}, function(){$$('text').value='';} );
	return false;
}
	</script>
</head>
<body>
<div data-role="page">
	<div data-role="header">
		<h1 style="letter-spacing: 0.3em;">聊天室</h1>
	</div>
	<div data-role="content">
		<div id="board" style="word-wrap:break-word;word-break:normal;"><p>&nbsp;</p></div>	
	</div>
	<div data-role="footer" style="position:fixed;left:0;bottom:0;width:100%">
		<form onsubmit="sendMsg($$('text').value); return false;" data-ajax="false">
			<input type="text" id="text" placeholder="Enter键发送文字" />
		</form>
	</div>
	<iframe id="frame" style="display:none">Iframe not supported</iframe>
</div>
</body>
</html>
<?php
if ( !isset($_REQUEST['user']) ) exit(); $user = $_REQUEST['user'];
ob_end_clean();    // Cancel show the client if calling API only
header("Cache-Control: no-cache, must-revalidate"); ob_end_flush();
mysql_connect("localhost","root","password"); mysql_select_db("test");
if ( isset($_REQUEST['msg']) ) {
	$msg = str_replace('\\','&#92;', htmlspecialchars($_REQUEST['msg']));
	mysql_query('INSERT INTO `chat`(`name`, `msg`) VALUES ("'.$user.'","'.$msg.'")');
	echo 'INSERT INTO `chat`(`name`, `msg`) VALUES ("'.$user.'","'.$msg.'")';
} else if ( isset($_GET['connect']) ) {
	$lastId = intval($_GET['connect']);
	set_time_limit(600);
	for ( $i=1; $i<=400; $i++ ) {
		$result = mysql_query('SELECT `id`,`name`,`msg` FROM `chat` WHERE id>'.$lastId.' LIMIT 15');
		while( $row = mysql_fetch_row($result) ) {
			pushMsg($row[0], $row[1], $row[2]);
			$lastId = max($row[0], $lastId);
		} usleep(600000);
	}
} else die();
function pushMsg($id, $user, $msg) {
	ob_start(); $msg = nl2br($msg);
	echo "<script type=\"text/javascript\">parent.onMsg('$user','$msg');parent.lastId=$id;</script>\n";
	echo str_repeat(' ',2000);
	ob_end_flush();
}
?>